version: "3.7"
services:
  expense-tracker-db:
    restart: always
    container_name: expense-tracker-db
    image:  postgres:14
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=expensedb

    volumes:
        - ./postgres/data:/var/lib/postgresql/data
        - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  expense-tracker-api:
    restart: on-failure
    build: ./
    image: spring-boot-expense-tracker
    container_name: expense-tracker-api
    expose:
      - "8082"
      - "5006"
    ports:
      - "8082:8082"
      - "5006:5006"

    env_file:
      - .env

    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      - expense-tracker-db